// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MakefileReader
{
    internal sealed partial class Vsix
    {
        public const string Id = "MakefileReader.9f1c63a8-cc87-46d8-bf60-aec085d9f577";
        public const string Name = "MakefileReader";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Nguyen Khai";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
