// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MakefileReader
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MakefileReaderString = "d5f00d0c-a5c4-4cba-ab1d-1d7921e4f56e";
        public static Guid MakefileReader = new Guid(MakefileReaderString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Edit_Makefile_Group = 0x0001;
        public const int View_OtherWindows_Makefile_Button_0 = 0x0002;
        public const int Edit_Makefile_Button_0 = 0x0003;
    }
}
